name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mysql-master:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: perpustakaanhb
    
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: 'npm ci'
      - name: Setup Database
        run: 'npm run migration'
      - name: Run Tests
        run: 'npm run test'
